import rawIconNodes from "generated/icon-nodes.json";
import type { Variant } from "@/lib/icons";
import type { IconNodeChild } from "@/lib/svg-path";

interface IconNodeEntry {
  node: IconNodeChild[];
  pascalName: string;
  variant: string;
}

// Keyed by kebab source name (e.g. "alert-circle") → variant → geometry.
// Generated by `pnpm gen-icon-nodes` from icons/**/*.svg.
// JSON.parse widens the tuple geometry to `(string | {...})[][]`, which doesn't
// structurally match the IconNodeChild tuple, so cast through `unknown`. The
// generator guarantees the shape.
const iconNodes = rawIconNodes as unknown as Record<
  string,
  Partial<Record<Variant, IconNodeEntry>>
>;

/** Every kebab icon name that has geometry, sorted. */
export const ICON_NODE_NAMES = Object.keys(iconNodes).sort((a, b) =>
  a.localeCompare(b)
);

/** Variants an icon's geometry exists in, in canonical order. */
export function getVariantsWithGeometry(name: string): Variant[] {
  const entry = iconNodes[name];
  if (!entry) {
    return [];
  }
  return (["stroke", "fill"] as const).filter((v) => v in entry);
}

/** Raw parsed geometry for an icon+variant, or null when absent. */
export function getIconGeometry(
  name: string,
  variant: Variant
): IconNodeChild[] | null {
  return iconNodes[name]?.[variant]?.node ?? null;
}

/** PascalCase component name for a kebab icon name + variant, or null. */
export function getPascalName(name: string, variant?: Variant): string | null {
  const entry = iconNodes[name];
  if (!entry) {
    return null;
  }
  const chosen = variant ? entry[variant] : (entry.stroke ?? entry.fill);
  return chosen?.pascalName ?? null;
}

/**
 * True when the icon's geometry is split across more than one top-level SVG
 * element (e.g. a `<path>` plus a separate `<circle>`) in any variant. Jedd
 * icons should ideally be a single flat element, so these are worth surfacing.
 */
export function isMultiElement(name: string): boolean {
  const entry = iconNodes[name];
  if (!entry) {
    return false;
  }
  return (["stroke", "fill"] as const).some(
    (v) => (entry[v]?.node.length ?? 0) > 1
  );
}

// Memoized set of every multi-element icon, so the picker can filter/badge
// without rescanning geometry each render.
let multiElementCache: Set<string> | null = null;

export function getMultiElementIconNames(): Set<string> {
  if (multiElementCache) {
    return multiElementCache;
  }
  multiElementCache = new Set(ICON_NODE_NAMES.filter(isMultiElement));
  return multiElementCache;
}
