import rawIconNodes from "generated/icon-nodes.json";
import type { Variant } from "@/lib/icons";
import type { IconNodeChild } from "@/lib/svg-path";

interface IconNodeEntry {
  node: IconNodeChild[];
  pascalName: string;
  variant: string;
}

// Keyed by kebab source name (e.g. "alert-circle") → variant → geometry.
// Generated by `pnpm gen-icon-nodes` from icons/**/*.svg.
// JSON.parse widens the tuple geometry to `(string | {...})[][]`, which doesn't
// structurally match the IconNodeChild tuple, so cast through `unknown`. The
// generator guarantees the shape.
const iconNodes = rawIconNodes as unknown as Record<
  string,
  Partial<Record<Variant, IconNodeEntry>>
>;

/** Every kebab icon name that has geometry, sorted. */
export const ICON_NODE_NAMES = Object.keys(iconNodes).sort((a, b) =>
  a.localeCompare(b)
);

/** Variants an icon's geometry exists in, in canonical order. */
export function getVariantsWithGeometry(name: string): Variant[] {
  const entry = iconNodes[name];
  if (!entry) {
    return [];
  }
  return (["stroke", "fill"] as const).filter((v) => v in entry);
}

/** Raw parsed geometry for an icon+variant, or null when absent. */
export function getIconGeometry(
  name: string,
  variant: Variant
): IconNodeChild[] | null {
  return iconNodes[name]?.[variant]?.node ?? null;
}

/** PascalCase component name for a kebab icon name, or null. */
export function getPascalName(name: string): string | null {
  const entry = iconNodes[name];
  const first = entry?.stroke ?? entry?.fill;
  return first?.pascalName ?? null;
}
